config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  devise_for :users
     resources :preps, only:[:index, :new, :create] do
       resources :tasks, only: [:index, :new, :create,:edit,:update] do
         resources :actives, only: [:index, :new, :create,:edit,:update] do 
           resources :reviews, only: [:index, :new, :create,:edit,:update] 
         end
       end
     end

     resources :preps, only:[:edit, :update, :destroy]
     resources :tasks, only:[:destroy]
     resources :actives, only:[:destroy]
     resources :reviews, only: [:destroy] 
      # resources :preps , only: [:index, :create, :edit, :update, :destroy] do
      #   resources :tasks , only: [:index, :create, :edit, :update, :destroy]
      # end
      #     resources :actives , only: [:index, :create, :edit, :update, :destroy]
      # end
end

app/models/active.rb
class Active < ApplicationRecord
  belongs_to :user
  belongs_to :prep
  belongs_to :task
  has_many :reviews,dependent: :destroy

  with_options presence: true do
    validates :way_1
    validates :way_2
    validates :way_3
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prep.rb
class Prep < ApplicationRecord
  belongs_to :user
  has_many :tasks,dependent: :destroy
  has_many :actives,dependent: :destroy
  has_many :reviews,dependent: :destroy

  with_options presence: true do
    validates :now
    validates :target
  end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :prep
  belongs_to :task
  belongs_to :active

  with_options presence: true do
    validates :rev_1
    validates :rev_2
    validates :rev_3
    validates :rev_4

  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :prep
  has_many :actives,dependent: :destroy
  has_many :reviews,dependent: :destroy
  
  with_options presence: true do
    validates :task_1
    validates :task_2
    validates :task_3
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :preps
  has_many :tasks
  has_many :actives
  has_many :reviews

  validates :nickname, presence: true
  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }

end

app/controllers/actives_controller.rb
class ActivesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @prep = Prep.find(params[:prep_id])
    @task = Task.find(params[:task_id]) 
    @active = Active.new
    @actives = Active.includes([:user,:prep,:task])
  end

  def create
    @prep = Prep.find(params[:prep_id])
    @task = Task.find(params[:task_id])
    @active = Active.new(active_params)
    @actives = Active.includes([:user,:prep,:task])
    if @active.valid?
      @active.save
      redirect_to "/preps/#{@active.prep.id}/tasks/#{@active.task.id}/actives"
    else
      render :index
    end
  end

  def edit
    @prep = Prep.find(params[:prep_id]) 
    @task = Task.find(params[:task_id]) 
    @active = Active.find(params[:id]) 
    redirect_to action: :index unless user_signed_in? && current_user.id == @prep.user_id
  end

  def update
    @prep = Prep.find(params[:prep_id]) 
    @task = Task.find(params[:task_id]) 
    @active = Active.find(params[:id]) 
    if @active.update(active_params)
       redirect_to prep_task_actives_path(@prep.id,@task.id,@active)
    else
       render :edit
    end
  end

  def destroy
    active = Active.find(params[:id])
    active.destroy
    redirect_to preps_path
  end
  
  private

  def active_params 
    params.require(:active).permit(:way_1, :way_2,:way_3).merge(user_id: current_user.id ,prep_id: params[:prep_id],task_id: params[:task_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname]) 
  end
end

app/controllers/preps_controller.rb
class PrepsController < ApplicationController
  before_action :authenticate_user!

  def index
    @prep = Prep.new
    @preps = Prep.includes(:user)
  end

  def create
    @preps = Prep.includes(:user)
    @prep = Prep.new(prep_params)
    if @prep.valid?
      @prep.save
      redirect_to preps_path(@prep)
    else
      render :index
    end
  end

  def edit
    @prep = Prep.find(params[:id]) 
    redirect_to action: :index unless user_signed_in? && current_user.id == @prep.user_id
  end

  def update
    @prep = Prep.find(params[:id])
    if @prep.update(prep_params)
       redirect_to preps_path(@prep)
    else
       render :edit
    end
  end

  def destroy
    prep = Prep.find(params[:id])
    prep.destroy
    redirect_to preps_path
  end

  private

  def prep_params
    params.require(:prep).permit(:now, :target).merge(user_id: current_user.id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @prep = Prep.find(params[:prep_id])
    @task = Task.find(params[:task_id]) 
    @active = Active.find(params[:active_id])
    @review = Review.new
    @reviews = Review.includes([:user,:prep,:task,:active])
  end

  def create
    @prep = Prep.find(params[:prep_id])
    @task = Task.find(params[:task_id])
    @active = Active.find(params[:active_id])
    @review = Review.new(review_params)
    @reviews = Review.includes([:user,:prep,:task,:active])
    if @review.valid?
      @review.save
      redirect_to "/preps/#{@review.prep.id}/tasks/#{@review.task.id}/actives/#{@review.active.id}/reviews"
    else
      render :index
    end
  end

  def edit
    @prep = Prep.find(params[:prep_id])
    @task = Task.find(params[:task_id]) 
    @active = Active.find(params[:active_id])  
    @review = Review.find(params[:id])  
    redirect_to action: :index unless user_signed_in? && current_user.id == @review.user_id
  end

  def update
    @prep = Prep.find(params[:prep_id])
    @task = Task.find(params[:task_id]) 
    @active = Active.find(params[:active_id])  
    @review = Review.find(params[:id])  
    if @review.update(review_params)
       redirect_to prep_task_active_reviews_path(@prep.id,@task.id,@active.id,@review)
    else
       render :edit
    end
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to preps_path
  end
  
  private

  def review_params
    params.require(:review).permit(:rev_1, :rev_2,:rev_3,:rev_4).merge(user_id: current_user.id ,prep_id: params[:prep_id],task_id: params[:task_id],active_id: params[:active_id])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @prep = Prep.find(params[:prep_id])
    @task = Task.new
    @tasks = Task.includes([:user,:prep])
  end

  def create
    @prep = Prep.find(params[:prep_id])
    @task = Task.new(task_params)
    @tasks = Task.includes([:user,:prep])
    if @task.valid?
      @task.save
      redirect_to "/preps/#{@task.prep.id}/tasks"
    else
      render :index
    end
  end

  def edit
    @prep = Prep.find(params[:prep_id])
    @task = Task.find(params[:id])
    redirect_to action: :index unless user_signed_in? && current_user.id == @task.user_id
  end
  
  def update
    @prep = Prep.find(params[:prep_id])
    @task = Task.find(params[:id])
    if @task.update(task_params)
       redirect_to prep_tasks_path(@prep.id,@task)
    else
       render :edit
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to preps_path
  end
  
  private

  def task_params 
    params.require(:task).permit(:task_1, :task_2,:task_3).merge(user_id: current_user.id ,prep_id: params[:prep_id])
  end


end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/actives_helper.rb
module ActivesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/preps_helper.rb
module PrepsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/actives/edit.html.erb
<div class="container-fluid bg-light d-flex flex-column" >
  <div class="container mb-auto">
  
    <h1 class="mt-4">Lesson3 課題の克服</h1>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

     <p>心が変われば、態度が変わる。態度が変われば、行動が変わる。<br>行動が変われば、習慣が変わる。習慣が変われば、人格が変わる。<br>人格が変われば、運命が変わる。運命が変われば、人生が変わる<br>出典不明</p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

    <p>Lesson2 での内容表示 <br>〜さんの夢への課題<br>いつまでに？: 3日間<br>何をする？: 日記を書く <br>どうやる？:一言書く<p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

      <%= form_with(model: [@prep, @task, @active], local: true) do |f| %>
      
        <%= render 'shared/error_messages', model:  f.object %>

        <div class="form-group mt-2">
          <%= f.label :way_1, "具体的に行動する時間を決める" %><br />
          <%= f.text_area :way_1, class: "form-control", placeholder: "(例)仕事帰りにやる" %>
        </div>
        <div class="form-group mt-2">
          <%= f.label :way_2, "具体的な場所を決める" %><br />
          <%= f.text_area :way_2, class: "form-control", placeholder: "(例)電車の中でやる" %>
        </div>
       <div class="form-group mt-2">
          <%= f.label :way_3, "具体的な効果を決める" %><br />
          <%= f.text_area :way_3, class: "form-control", placeholder: "(例)何かわからないけど、昨日よりもよくなるかもしれない" %>
        </div>

        <div class="text-center mb-5">
          <%= f.submit "記録する" ,class:"btn btn-block send-button tx-tfm" %>
        </div>
      <% end %>

app/views/actives/index.html.erb
<div class="container-fluid bg-light d-flex flex-column" >
  <div class="container mb-auto">
  
    <h1 class="mt-4">Lesson3 課題の克服</h1>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

     <p>心が変われば、態度が変わる。態度が変われば、行動が変わる。<br>行動が変われば、習慣が変わる。習慣が変われば、人格が変わる。<br>人格が変われば、運命が変わる。運命が変われば、人生が変わる<br>出典不明</p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

    <p>Lesson2 での内容表示 <br>〜さんの夢への課題<br>いつまでに？: 3日間<br>何をする？: 日記を書く <br>どうやる？:一言書く<p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

      <%= form_with(model: [@prep, @task, @active], local: true) do |f| %>
      
        <%= render 'shared/error_messages', model:  f.object %>

        <div class="form-group mt-2">
          <%= f.label :way_1, "具体的に行動する時間を決める" %><br />
          <%= f.text_area :way_1, class: "form-control", placeholder: "(例)仕事帰りにやる" %>
        </div>
        <div class="form-group mt-2">
          <%= f.label :way_2, "具体的な場所を決める" %><br />
          <%= f.text_area :way_2, class: "form-control", placeholder: "(例)電車の中でやる" %>
        </div>
       <div class="form-group mt-2">
          <%= f.label :way_3, "具体的な効果を決める" %><br />
          <%= f.text_area :way_3, class: "form-control", placeholder: "(例)何かわからないけど、昨日よりもよくなるかもしれない" %>
        </div>

        <div class="text-center mb-5">
          <%= f.submit "記録する" ,class:"btn btn-block send-button tx-tfm" %>
        </div>
      <% end %>

  </div>
      <div class="form_tag"> 
        <div class="col-md-12 ">
          <div class="login-or">
            <hr class="hr-or">
          </div>
        </div>
      </div>

          <div class="prep_list">
          <ul class="preps_lists">

            
              <% @actives.each do |active|%>
                <% if user_signed_in? && current_user.id == active.user_id %>
                <li class="preps_list">
                  <%= active.way_1 %>
                  <%= active.way_2 %>
                  <%= active.way_3 %>
                  <%= link_to "Lesson4へ すすむ",prep_task_active_reviews_path(@prep.id,@task.id,active.id) %>
                  <%= link_to "編集",edit_prep_task_active_path(@prep,@task,active) %>
                  <%=  button_to "削除",active_path(active),method: :delete %>
                </li>
              <% end%>
            <% end %>

          </ul>
        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tekagami</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <div class= "container-fluid bg-light mb-auto">
    <nav class="navbar navbar-expand-sm navbar-light sticky-top bg-light">
      <a class="sign">
        <%= link_to image_tag("logo_4d5156.png",:size=>"108x45",class: "wv-heading--title"), "/" %>
      </a>    
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse justify-content-end " id="navbarNavAltMarkup">
        <div class="navbar-nav" >
         <% if user_signed_in? %>
          <%= link_to current_user.nickname,"#" ,class: "nav-link"%> 
          <%= link_to "扉を開く", preps_path ,class: "nav-link"  %>
         
          <%= link_to "Step 1", "#" ,class: "nav-link"  %>
          <%= link_to "Step 2", "#" ,class: "nav-link" %> 
          <%= link_to "Step 3", "#" ,class: "nav-link"  %>
          <%= link_to "Step 4", "#" ,class: "nav-link"  %>
          <%= link_to "log_out", destroy_user_session_path ,:method => :get ,class: "nav-link",remote: true  %>
         <% else %>
          <%= link_to "intro", "#" ,class: "nav-link mr-2"  %>
          <%= link_to "prof", "#" ,class: "nav-link mr-2"  %>
          <%= link_to "log_in", new_user_session_path ,class: "nav-link mr-2" %>
          <%= link_to "sign_up", new_user_registration_path ,class: "nav-link order-2 mr-2" %>
         <% end %>
        </div>
      </div>
    </nav>

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
   
    <%= yield %>
    
      <div class="footer bg-light ">
        <div class= "footer_space">
          <div class="sign text-center mb-1">
            <%= link_to image_tag("logo_4d5156.png",:size=>"90x34",class: "wv-heading--title"), "/" %>
          </div>    
          <p class="text-center">Copyright©2020 Tekagami,All Rights Reserved.</p>
        </div>
      </div>
  </div>
</body>

</html>

app/views/preps/edit.html.erb
<div class="container-fluid bg-light d-flex flex-column" >
  <div class="container mb-auto">
  
    <h1 class="mt-4"> edit Lesson1 現実と夢を記述する</h1>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

     <p>未来を語る前に、今の現実を知らなければならない<br>
    現実からしかスタートできないからである。<br>by P.F.ドラッカー</p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>
    
    <p>もし、すでに lesson4まで終わっている場合表示する<br>Lesson4 での内容表示<br> 前回の〜さんの克服した現実の結果<br>どうなった?: AがBとなった <br>心の具合は?: わくわくした<p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

      <%= form_with(model: @prep,local: true) do |f| %>

        <%= render 'shared/error_messages', model:  f.object %>

        <div class="form-group mt-2">
          <%= f.label :now, "ゴールを目指している途中の気持ちを書いてみる" %><br />
          <%= f.text_area :now, class: "form-control", placeholder: "(例)なんかモヤモヤしている" %>
        </div>
        <div class="form-group mt-2">
          <%= f.label :target, "ゴールを達成した未来の気持ちを書いてみる" %><br />
          <%= f.text_area :target, class: "form-control", placeholder: "(例)なんかかいい感じ" %>
        </div>

        <div class="text-center mb-5">
          <%= f.submit "記録する" ,class:"btn btn-block send-button tx-tfm" %>
        </div>
      <% end %>

      <div class="form_tag"> 
        <div class="col-md-12 ">
          <div class="login-or">
            <hr class="hr-or">
          </div>
        </div>
         

  </div>
</div>

app/views/preps/index.html.erb
<div class="container-fluid bg-light d-flex flex-column" >
  <div class="container mb-auto">
  
    <h1 class="mt-4">Lesson1 現実と夢を記述する</h1>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

     <p>未来を語る前に、今の現実を知らなければならない<br>
    現実からしかスタートできないからである。<br>by P.F.ドラッカー</p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>
    
    <p>もし、すでに lesson4まで終わっている場合表示する<br>Lesson4 での内容表示<br> 前回の〜さんの克服した現実の結果<br>どうなった?: AがBとなった <br>心の具合は?: わくわくした<p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

      <%= form_with(model: @prep,local: true) do |f| %>

        <%= render 'shared/error_messages', model:  f.object %>

        <div class="form-group mt-2">
          <%= f.label :now, "ゴールを目指している途中の気持ちを書いてみる" %><br />
          <%= f.text_area :now, class: "form-control", placeholder: "(例)なんかモヤモヤしている" %>
        </div>
        <div class="form-group mt-2">
          <%= f.label :target, "ゴールを達成した未来の気持ちを書いてみる" %><br />
          <%= f.text_area :target, class: "form-control", placeholder: "(例)なんかかいい感じ" %>
        </div>

        <div class="text-center mb-5">
          <%= f.submit "記録する" ,class:"btn btn-block send-button tx-tfm" %>
        </div>
      <% end %>

      <div class="form_tag"> 
        <div class="col-md-12 ">
          <div class="login-or">
            <hr class="hr-or">
          </div>
        </div>
         
        <div class="prep_list">
          <ul class="preps_lists">

              <% @preps.each do |prep|%>
                <% if user_signed_in? && current_user.id == prep.user_id %>
                  <li class="preps_list">
                    <%= prep.now %>
                    <%= prep.target %>
                    <%= link_to "Lesson2へ すすむ",prep_tasks_path(prep.id) %>
                    <%= link_to "編集",edit_prep_path(prep) %>
                    <%= button_to "削除",prep_path(prep) ,method: :delete %>
                  </li>
                <% end%>
              <% end %>

          </ul>
        </div>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="container-fluid bg-light d-flex flex-column" >
  <div class="container mb-auto">
  
    <h1 class="mt-4">Lesson4 克服し現実へ</h1>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

     <p>あなたにとって大切で重要な刺激的なことをやっているならば<br>あなたは頑張る必要はない<br>Visionがあなたを突き動かしてくれる<br>by スティーブ・ジョブズ</p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

    <p>Lesson3 での内容表示 <br>〜さんの夢への課題<br>いつやる？: 会社帰り<br>どこでする: 電車の中で <br>どんな気持ち:わくわく<p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

      <%= form_with(model: [@prep, @task, @active, @review], local: true) do |f| %>
      
        <%= render 'shared/error_messages', model:  f.object %>

        <div class="form-group mt-2">
          <%= f.label :rev_1, "どれだけ夢に近づいたか" %><br />
          <%= f.text_area :rev_1, class: "form-control", placeholder: "(例)最初よりも少しだけ、なにか良くなった" %>
        </div>
        <div class="form-group mt-2">
          <%= f.label :rev_2, "行動して止めようとしたこと" %><br />
          <%= f.text_area :rev_2, class: "form-control", placeholder: "(例)朝時間の有効に使うため、23時までに就寝するようにする" %>
        </div>
       <div class="form-group mt-2">
          <%= f.label :rev_3, "行動して方法を変えたほうがいいもの" %><br />
          <%= f.text_area :rev_3, class: "form-control", placeholder: "(例)朝は満員電車のため、聴く学習を取り入れる" %>
        </div>
       <div class="form-group mt-2">
          <%= f.label :rev_4, "行動して新しく初めてみようとしていること" %><br />
          <%= f.text_area :rev_4, class: "form-control", placeholder: "(例)タイマーを使って時間を区切ってみる" %>
        </div>

        <div class="text-center mb-5">
          <%= f.submit "記録する" ,class:"btn btn-block send-button tx-tfm" %>
        </div>
      <% end %>

  </div>
      <div class="form_tag"> 
        <div class="col-md-12 ">
          <div class="login-or">
            <hr class="hr-or">
          </div>
        </div>
      </div>

          <div class="prep_list">
          <ul class="preps_lists">

           
              <% @reviews.each do |review|%>
                <% if user_signed_in? && current_user.id == review.user_id %>
                <li class="preps_list">
                  <%= review.rev_1 %>
                  <%= review.rev_2 %>
                  <%= review.rev_3 %>
                  <%= link_to "ホームに戻る","/" %>
                  <%= link_to "編集",edit_prep_task_active_review_path(@prep,@task,@active,review) %>
                  <%=  button_to "削除",review_path(review),method: :delete %>
                </li>
              <% end%>
            <% end %>

          </ul>
        </div>
</div>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log_in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/tasks/index.html.erb
<div class="container-fluid bg-light d-flex flex-column" >
  <div class="container mb-auto">
  
    <h1 class="mt-4">Lesson2 夢への課題を記述する</h1>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

     <p>人類永遠の課題は<br>起きている時間をどのように構成するかだ<br>by エリック・バーン</p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

    <p>Lesson1 での内容表示 <br>〜さんの夢への課題<br>現在:なぜか悲しい<br>未来:わくわくしたい<p>

    <div class="col-md-12 ">
      <div class="login-or">
          <hr class="hr-or">
      </div>
    </div>

      <%= form_with(model: [@prep, @task], local: true) do |f| %>
      
        <%= render 'shared/error_messages', model:  f.object %>

        <div class="form-group mt-2">
          <%= f.label :task_1, "進んだぶんゴールに近づく、どれだけやろうか" %><br />
          <%= f.text_area :task_1, class: "form-control", placeholder: "(例)3日間だけ" %>
        </div>
        <div class="form-group mt-2">
          <%= f.label :task_2, "行動したぶんゴールに近づく、なにをしようか" %><br />
          <%= f.text_area :task_2, class: "form-control", placeholder: "(例)とりあえず日記をつける" %>
        </div>
       <div class="form-group mt-2">
          <%= f.label :task_3, "考えたぶんゴールに近づく、どうやろうか" %><br />
          <%= f.text_area :task_3, class: "form-control", placeholder: "(例)今日の感情を一言だけ書いてみよう" %>
        </div>

        <div class="text-center mb-5">
          <%= f.submit "記録する" ,class:"btn btn-block send-button tx-tfm" %>
        </div>
      <% end %>

  </div>
      <div class="form_tag"> 
        <div class="col-md-12 ">
          <div class="login-or">
            <hr class="hr-or">
          </div>
        </div>
      </div>

          <div class="prep_list">
          <ul class="preps_lists">

            
              <% @tasks.each do |task|%>
                <% if user_signed_in? && current_user.id == task.user_id %>
                <li class="preps_list">
                  <%= task.task_1 %>
                  <%= task.task_2 %>
                  <%= task.task_3 %>
                  <%= link_to "Lesson3へ すすむ",prep_task_actives_path(@prep,task.id) %>
                  <%= link_to "編集",edit_prep_task_path(@prep,task) %>
                  <%= button_to "削除",task_path(task) ,method: :delete %>
                </li>
              <% end%>
            <% end %>

          </ul>
        </div>
</div>